server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: poll_sa
    password: poll123
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

userService:
  url: 127.0.0.1:8081